import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/auth-options";
import { redirect } from "next/navigation";
import { WebPlayer } from "@/app/(logged-in)/web-player";
import { Sidenav } from "@/components/ui/sidenav";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/login");
  }
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "grid-container relative overflow-hidden min-h-screen bg-black  p-1 gap-2 text-white"
        )}
      >
        <Sidenav />
        <main className="flex h-full flex-col overflow-hidden rounded-md bg-black ">
          {children}
        </main>
        <WebPlayer />
      </body>
    </html>
  );
}
