import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/auth-options";
import { redirect } from "next/navigation";
import { WebPlayer } from "@/app/(logged-in)/web-player";
import { twMerge } from "tailwind-merge";
import { Sidenav } from "@/components/ui/sidenav";
import { Navbar } from "@/components/ui/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/login");
  }
  return (
    <html lang="en">
      <body
        className={twMerge(
          inter.className,
          "grid grid-cols-[305px_1fr] grid-rows-[1fr_80px] min-h-screen grid-flow-row relative bg-black"
        )}
      >
        <Sidenav />
        <main className="col-span-1 row-span-1 bg-black py-2 h-full w-full rounded-lg">
          <div className="bg-[#121212] p-4 text-white h-full rounded-lg">
            <Navbar />
            {children}
          </div>
        </main>
        <WebPlayer />
      </body>
    </html>
  );
}
