import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/auth-options";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);
  if (session) {
    redirect("/home");
  }
  return (
    <html lang="en" className="h-full">
      <body className="h-full w-full">{children}</body>
    </html>
  );
}
